# Generated by Django 2.1.7 on 2019-04-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('moderated', 'Moderated')], default='visible', max_length=20)),
                ('moderation_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fonction', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('linkedin', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=500)),
                ('mission', models.TextField(max_length=1000)),
                ('addresse', models.CharField(max_length=500)),
                ('contact_name', models.CharField(max_length=500)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('secteur_activite', models.CharField(choices=[('1', 'Services'), ('2', 'Education'), ('3', 'Banque'), ('4', 'Assurances'), ('5', 'Medical')], max_length=1000)),
                ('urls_en', models.CharField(max_length=500)),
                ('urls_linkedin', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1500)),
                ('lieu', models.CharField(max_length=500)),
                ('sale', models.CharField(max_length=500)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('title', models.CharField(default='ETSMTL', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EvenementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=500)),
                ('liste_email', models.CharField(max_length=500)),
                ('event', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='core.Evenement')),
                ('hunter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Joindre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_representant', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('short_description', models.TextField(max_length=1000)),
                ('date_de_debut', models.CharField(max_length=500)),
                ('dete_de_fin', models.CharField(max_length=500)),
                ('salaire', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('moderated', 'Moderated')], default='hidden', max_length=20)),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=500)),
                ('upload_cv', models.ImageField(blank=True, upload_to='documents/')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postules', to='core.Offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.OfferCategory'),
        ),
        migrations.AddField(
            model_name='offer',
            name='evenement',
            field=models.ManyToManyField(to='core.Evenement'),
        ),
        migrations.AddField(
            model_name='offer',
            name='hunter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.EvenementCategory'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='hunter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employe',
            name='evenement',
            field=models.ManyToManyField(to='core.Evenement'),
        ),
        migrations.AddField(
            model_name='employe',
            name='hunter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Evenement'),
        ),
    ]
