# Generated by Django 2.1.7 on 2019-04-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='category',
        ),
    ]
